#Header
menu:
  Home: /
  Blog: /archives
rss: /atom.xml

# Disqus Comments Shortname
disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Miscellaneous
favicon: /images/favicon.ico
twitter:
google_plus:
facebook:
fb_admins:
fb_app_id:
